package problems;

import java.math.BigDecimal;
import java.util.HashMap;

/*
Problem 29
25 October 2002

Consider all integer combinations of ab for 2  a  5 and 2  b  5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?
 */



public class TwentyNine {
	
	private static final int MAX = 100;
	private static final int MIN = 2;

	public static void main(String args[]){
		Helper helper = new Helper();
		HashMap<String, String> map = new HashMap<String, String>();
		for (int a=MIN; a<=MAX;a++){
			for (int b=MIN; b<=MAX;b++){
				map.put(helper.power(new BigDecimal(a), new BigDecimal(b)).toPlainString(), "");
			}
		}
		System.out.println("Answer: " + map.size());
	}

}
