package problems;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


public class Two {
	
	public static void main(String args[]){
		
		int a =1;
		int b =2;
		int c = 0;
		int sum = b;
				
		do {	
			c = a+b;
			if (c%2==0){
				sum = sum +c;
			}
		
			System.out.println(a +" "+b+" "+c +"   "+sum);
			a=b;
			b=c;
			
		}while (c<4000000);
		
		System.out.print(sum);
		
	}
	
/*	
	public static void kot(String args[]){
		
		int a =1;
		int b =2;
		int c = 0;
		int sum = b;
		boolean add = false;
				
		do {	
			c = a+b;
			if (add){
				sum = sum +c;
				add=false;
			}
			else
				add=true;
			System.out.println(a +" "+b+" "+c +"   "+sum);
			a=b;
			b=c;
			
		}while (c<4000000);
		
		System.out.print(sum);
		
	}
*/
}
